conf_filename: /Users/rmcgibbo/local/diffusion/null.pdb
trajs:
- converted_from: []
  errors: null
  id: 0
  length: 1000
  path: /Users/rmcgibbo/local/diffusion/project/Trajectories/trj0.lh5
- converted_from: []
  errors: null
  id: 1
  length: 1000
  path: /Users/rmcgibbo/local/diffusion/project/Trajectories/trj1.lh5
- converted_from: []
  errors: null
  id: 2
  length: 1000
  path: /Users/rmcgibbo/local/diffusion/project/Trajectories/trj2.lh5
- converted_from: []
  errors: null
  id: 3
  length: 1000
  path: /Users/rmcgibbo/local/diffusion/project/Trajectories/trj3.lh5
- converted_from: []
  errors: null
  id: 4
  length: 1000
  path: /Users/rmcgibbo/local/diffusion/project/Trajectories/trj4.lh5
- converted_from: []
  errors: null
  id: 5
  length: 1000
  path: /Users/rmcgibbo/local/diffusion/project/Trajectories/trj5.lh5
- converted_from: []
  errors: null
  id: 6
  length: 1000
  path: /Users/rmcgibbo/local/diffusion/project/Trajectories/trj6.lh5
- converted_from: []
  errors: null
  id: 7
  length: 1000
  path: /Users/rmcgibbo/local/diffusion/project/Trajectories/trj7.lh5
- converted_from: []
  errors: null
  id: 8
  length: 1000
  path: /Users/rmcgibbo/local/diffusion/project/Trajectories/trj8.lh5
- converted_from: []
  errors: null
  id: 9
  length: 1000
  path: /Users/rmcgibbo/local/diffusion/project/Trajectories/trj9.lh5
